extends:
  - airbnb-base
plugins:
  - import
  - jest
rules:
  arrow-body-style: 0
  no-underscore-dangle: 0
  no-restricted-syntax: 0
  no-use-before-define: 0
globals:
  __: true
env:
  jest:
    globals: true
